import React,{useContext} from 'react'; //this components render a group of buttons based on the emojis
import { REACTION_OBJECTS } from '../state/types';
import context from '../context';//gives access to the pub/sub object
import { createReaction } from '../state/actions';

function CreateReaction({messageId}){
    const {state:{username},pubsub:{publish}} = useContext(context);
    const publishReaction = ({type, emoji})=>()=>{
        //result = publish to the pub sub system of an object with the create Reaction action creator
       
        publish(createReaction({type,emoji, username,messageId}));//we pass a reaction item generated by using the createreaction action creator
        //the id is passedas props from the messageboard
    }

    return(<>
    <div className='CreateReaction'>
        {REACTION_OBJECTS.map(({type,emoji})=>{
            return(<span 
                    key={type}
                    onClick={publishReaction({type,emoji})}>
                    {emoji}
                    </span>)
        })}
    </div>
    </>)
}

export default CreateReaction;
